/**
 * Shared prop interfaces for Nubisco UI components.
 *
 * Hierarchy:
 *
 *   IDefaultProps
 *     └── IHumanInputComponent
 *           └── IFieldComponent  (+ IWithLabel + IWithMessages + IWithFieldAppearance)
 *                 └── IReadableFieldComponent
 *
 * Compose these interfaces in component `.d.ts` files rather than redeclaring
 * common props. This keeps definitions DRY and feeds intellisense with the
 * JSDoc descriptions below.
 */

// #region IDefaultProps
/** Any component that can be identified by an explicit DOM id. */
interface IDefaultProps {
  /**
   * Explicit element id.
   * When omitted, a deterministic id is auto-generated by `useStableId()` from the
   * component type and `name` prop — e.g. `nb-text-input-email`.
   */
  id?: string
}
// #endregion IDefaultProps

// #region IWithMessages
/** Components that carry validation / feedback messages below the field. */
interface IWithMessages {
  /** Validation error — takes precedence over `warning` and `helper` when set. */
  error?: string
  /** Non-blocking caution message — shown only when `error` is absent. */
  warning?: string
  /** Contextual hint displayed when neither `error` nor `warning` is set. */
  helper?: string
}
// #endregion IWithMessages

// #region IWithLabel
/** Components that render a user-visible label. */
interface IWithLabel {
  /** Label text rendered above (`default` variant) or inside (`fluid` variant) the field. */
  label?: string
}
// #endregion IWithLabel

// #region IWithFieldAppearance
/** Components that support the standard field presentation variants and sizes. */
interface IWithFieldAppearance {
  /**
   * Presentation variant:
   * - `default` — label above, message below (standard style).
   * - `fluid`   — label and status icon inside the field box.
   */
  variant?: 'default' | 'fluid'
  /** Control size. */
  size?: 'sm' | 'md' | 'lg'
}
// #endregion IWithFieldAppearance

// #region IHumanInputComponent
/**
 * Interactive form control that participates in form submission and can be
 * disabled or marked as required.
 */
interface IHumanInputComponent extends IDefaultProps {
  /**
   * HTML `name` attribute forwarded to the native input.
   * Also drives auto-generated IDs when `id` is omitted:
   * `{component-type}-{name}` — e.g. `nb-select-country`.
   */
  name?: string
  /** Prevents interaction and visually dims the control. */
  disabled?: boolean
  /** Marks the field as mandatory — surfaced in the label and `aria-required`. */
  required?: boolean
}
// #endregion IHumanInputComponent

// #region IFieldComponent
/**
 * Full labeled field with placeholder text, validation messages, variant and
 * size. The baseline for text-like, number, and select inputs.
 */
interface IFieldComponent
  extends
    IHumanInputComponent,
    IWithLabel,
    IWithMessages,
    IWithFieldAppearance {
  /** Placeholder text shown when the field has no value. */
  placeholder?: string
}
// #endregion IFieldComponent

// #region IReadableFieldComponent
/**
 * Extends `IFieldComponent` with a read-only mode: the value is visible and
 * copyable but cannot be changed by the user.
 */
interface IReadableFieldComponent extends IFieldComponent {
  /** Makes the field read-only — value is visible but not editable. */
  readonly?: boolean
}
// #endregion IReadableFieldComponent

export {
  IDefaultProps,
  IWithMessages,
  IWithLabel,
  IWithFieldAppearance,
  IHumanInputComponent,
  IFieldComponent,
  IReadableFieldComponent,
}
